plugin 'cocoapods-acknowledgements'
pod "MSColorPicker"
platform :ios, '12.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
            config.build_settings['SWIFT_VERSION'] = '5.1'
            config.build_settings['DEVELOPMENT_TEAM'] = '3UUB5NM43K'
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-DSUPPRESS_WARNINGS'
            config.build_settings['OTHER_CFLAGS'] = '-DZXING_EXPERIMENTAL_API -DWITH_QRCODE -DZXING_READERS -DZXING_WRITERS -DZXING_USE_ZINT -DZXING_USE_BUNDLED_ZINT'
        end
    end
end