plugin 'cocoapods-acknowledgements'
platform :ios, '12.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
            config.build_settings['SWIFT_VERSION'] = '5.1'
            config.build_settings['DEVELOPMENT_TEAM'] = '3UUB5NM43K'
        end
    end
end