name: 'release'

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        default: patch
        description: What kind of version upgrade
        options: 
        - none
        - code
        - patch
        - minor
        - major
      documentscanner:
        description: 'Release DocumentScanner'
        required: true
        default: true
        type: boolean
      cardwallet:
        description: 'Release CardWallet'
        required: true
        default: true
        type: boolean
      ios:
        description: 'Release for iOS'
        required: true
        default: true
        type: boolean
      android:
        description: 'Release for Android'
        required: true
        default: true
        type: boolean

jobs:
  release-documentscanner-android:
    uses: Akylas/app-tools/.github/workflows/release_android.yml@main
    if: github.event.inputs.android == 'true' && github.event.inputs.documentscanner == 'true'
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit

  release-cardwallet-android:
    uses: Akylas/app-tools/.github/workflows/release_android.yml@main
    if: github.event.inputs.android == 'true' && github.event.inputs.cardwallet == 'true'
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit

  release-documentscanner-ios:
    uses: Akylas/app-tools/.github/workflows/release_android.yml@main
    if: github.event.inputs.ios == 'true' && github.event.inputs.documentscanner == 'true'
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit
    
  release-cardwallet-ios:
    uses: Akylas/app-tools/.github/workflows/release_android.yml@main
    if: github.event.inputs.ios == 'true' && github.event.inputs.cardwallet == 'true'
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit
